// flow-typed signature: c5c523a0f04da686dd855de4b0f2afa3
// flow-typed version: <<STUB>>/graphql-fragments_v^0.1.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-fragments'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-fragments' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-fragments/Fragment' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-fragments/Fragment.js' {
  declare module.exports: $Exports<'graphql-fragments/Fragment'>;
}
declare module 'graphql-fragments/index' {
  declare module.exports: $Exports<'graphql-fragments'>;
}
declare module 'graphql-fragments/index.js' {
  declare module.exports: $Exports<'graphql-fragments'>;
}
