// flow-typed signature: e1518eba0b9eed31156fa9ac4a4c4dad
// flow-typed version: <<STUB>>/graphql-tag_v^1.3.1/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-tag'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-tag' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-tag/bundledParser' {
  declare module.exports: any;
}

declare module 'graphql-tag/bundledPrinter' {
  declare module.exports: any;
}

declare module 'graphql-tag/loader' {
  declare module.exports: any;
}

declare module 'graphql-tag/parser' {
  declare module.exports: any;
}

declare module 'graphql-tag/printer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-tag/bundledParser.js' {
  declare module.exports: $Exports<'graphql-tag/bundledParser'>;
}
declare module 'graphql-tag/bundledPrinter.js' {
  declare module.exports: $Exports<'graphql-tag/bundledPrinter'>;
}
declare module 'graphql-tag/index' {
  declare module.exports: $Exports<'graphql-tag'>;
}
declare module 'graphql-tag/index.js' {
  declare module.exports: $Exports<'graphql-tag'>;
}
declare module 'graphql-tag/loader.js' {
  declare module.exports: $Exports<'graphql-tag/loader'>;
}
declare module 'graphql-tag/parser.js' {
  declare module.exports: $Exports<'graphql-tag/parser'>;
}
declare module 'graphql-tag/printer.js' {
  declare module.exports: $Exports<'graphql-tag/printer'>;
}
