// flow-typed signature: 93c4231910d141c15b4b73df0770a1e8
// flow-typed version: <<STUB>>/graphql-server-koa_v^1.1.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-server-koa'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-server-koa' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-server-koa/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-server-koa/dist/index.js' {
  declare module.exports: $Exports<'graphql-server-koa/dist/index'>;
}
