// flow-typed signature: 0cb9c09de377a5ec34c8d59b7cd3b092
// flow-typed version: <<STUB>>/nightmare_v^2.10.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nightmare'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nightmare' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nightmare/example' {
  declare module.exports: any;
}

declare module 'nightmare/lib/actions' {
  declare module.exports: any;
}

declare module 'nightmare/lib/frame-manager' {
  declare module.exports: any;
}

declare module 'nightmare/lib/ipc' {
  declare module.exports: any;
}

declare module 'nightmare/lib/javascript' {
  declare module.exports: any;
}

declare module 'nightmare/lib/nightmare' {
  declare module.exports: any;
}

declare module 'nightmare/lib/preload' {
  declare module.exports: any;
}

declare module 'nightmare/lib/runner' {
  declare module.exports: any;
}

declare module 'nightmare/test/files/globals' {
  declare module.exports: any;
}

declare module 'nightmare/test/files/jquery-1.9.0.min' {
  declare module.exports: any;
}

declare module 'nightmare/test/files/jquery-2.1.1.min' {
  declare module.exports: any;
}

declare module 'nightmare/test/files/nightmare-created' {
  declare module.exports: any;
}

declare module 'nightmare/test/files/nightmare-error' {
  declare module.exports: any;
}

declare module 'nightmare/test/files/nightmare-unended' {
  declare module.exports: any;
}

declare module 'nightmare/test/fixtures/preload/index' {
  declare module.exports: any;
}

declare module 'nightmare/test/index' {
  declare module.exports: any;
}

declare module 'nightmare/test/server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nightmare/example.js' {
  declare module.exports: $Exports<'nightmare/example'>;
}
declare module 'nightmare/lib/actions.js' {
  declare module.exports: $Exports<'nightmare/lib/actions'>;
}
declare module 'nightmare/lib/frame-manager.js' {
  declare module.exports: $Exports<'nightmare/lib/frame-manager'>;
}
declare module 'nightmare/lib/ipc.js' {
  declare module.exports: $Exports<'nightmare/lib/ipc'>;
}
declare module 'nightmare/lib/javascript.js' {
  declare module.exports: $Exports<'nightmare/lib/javascript'>;
}
declare module 'nightmare/lib/nightmare.js' {
  declare module.exports: $Exports<'nightmare/lib/nightmare'>;
}
declare module 'nightmare/lib/preload.js' {
  declare module.exports: $Exports<'nightmare/lib/preload'>;
}
declare module 'nightmare/lib/runner.js' {
  declare module.exports: $Exports<'nightmare/lib/runner'>;
}
declare module 'nightmare/test/files/globals.js' {
  declare module.exports: $Exports<'nightmare/test/files/globals'>;
}
declare module 'nightmare/test/files/jquery-1.9.0.min.js' {
  declare module.exports: $Exports<'nightmare/test/files/jquery-1.9.0.min'>;
}
declare module 'nightmare/test/files/jquery-2.1.1.min.js' {
  declare module.exports: $Exports<'nightmare/test/files/jquery-2.1.1.min'>;
}
declare module 'nightmare/test/files/nightmare-created.js' {
  declare module.exports: $Exports<'nightmare/test/files/nightmare-created'>;
}
declare module 'nightmare/test/files/nightmare-error.js' {
  declare module.exports: $Exports<'nightmare/test/files/nightmare-error'>;
}
declare module 'nightmare/test/files/nightmare-unended.js' {
  declare module.exports: $Exports<'nightmare/test/files/nightmare-unended'>;
}
declare module 'nightmare/test/fixtures/preload/index.js' {
  declare module.exports: $Exports<'nightmare/test/fixtures/preload/index'>;
}
declare module 'nightmare/test/index.js' {
  declare module.exports: $Exports<'nightmare/test/index'>;
}
declare module 'nightmare/test/server.js' {
  declare module.exports: $Exports<'nightmare/test/server'>;
}
