// flow-typed signature: 6ae04763e81bb36df50d1b4dfd2f4be2
// flow-typed version: <<STUB>>/redux-logic_v^0.12.2/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-logic'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-logic' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-logic/build-es/createLogic' {
  declare module.exports: any;
}

declare module 'redux-logic/build-es/createLogicAction$' {
  declare module.exports: any;
}

declare module 'redux-logic/build-es/createLogicMiddleware' {
  declare module.exports: any;
}

declare module 'redux-logic/build-es/index' {
  declare module.exports: any;
}

declare module 'redux-logic/build-es/logicWrapper' {
  declare module.exports: any;
}

declare module 'redux-logic/build-es/utils' {
  declare module.exports: any;
}

declare module 'redux-logic/build-lib/createLogic' {
  declare module.exports: any;
}

declare module 'redux-logic/build-lib/createLogicAction$' {
  declare module.exports: any;
}

declare module 'redux-logic/build-lib/createLogicMiddleware' {
  declare module.exports: any;
}

declare module 'redux-logic/build-lib/index' {
  declare module.exports: any;
}

declare module 'redux-logic/build-lib/logicWrapper' {
  declare module.exports: any;
}

declare module 'redux-logic/build-lib/utils' {
  declare module.exports: any;
}

declare module 'redux-logic/dist/redux-logic' {
  declare module.exports: any;
}

declare module 'redux-logic/dist/redux-logic.min' {
  declare module.exports: any;
}

declare module 'redux-logic/src/createLogic' {
  declare module.exports: any;
}

declare module 'redux-logic/src/createLogicAction$' {
  declare module.exports: any;
}

declare module 'redux-logic/src/createLogicMiddleware' {
  declare module.exports: any;
}

declare module 'redux-logic/src/index' {
  declare module.exports: any;
}

declare module 'redux-logic/src/logicWrapper' {
  declare module.exports: any;
}

declare module 'redux-logic/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-logic/build-es/createLogic.js' {
  declare module.exports: $Exports<'redux-logic/build-es/createLogic'>;
}
declare module 'redux-logic/build-es/createLogicAction$.js' {
  declare module.exports: $Exports<'redux-logic/build-es/createLogicAction$'>;
}
declare module 'redux-logic/build-es/createLogicMiddleware.js' {
  declare module.exports: $Exports<'redux-logic/build-es/createLogicMiddleware'>;
}
declare module 'redux-logic/build-es/index.js' {
  declare module.exports: $Exports<'redux-logic/build-es/index'>;
}
declare module 'redux-logic/build-es/logicWrapper.js' {
  declare module.exports: $Exports<'redux-logic/build-es/logicWrapper'>;
}
declare module 'redux-logic/build-es/utils.js' {
  declare module.exports: $Exports<'redux-logic/build-es/utils'>;
}
declare module 'redux-logic/build-lib/createLogic.js' {
  declare module.exports: $Exports<'redux-logic/build-lib/createLogic'>;
}
declare module 'redux-logic/build-lib/createLogicAction$.js' {
  declare module.exports: $Exports<'redux-logic/build-lib/createLogicAction$'>;
}
declare module 'redux-logic/build-lib/createLogicMiddleware.js' {
  declare module.exports: $Exports<'redux-logic/build-lib/createLogicMiddleware'>;
}
declare module 'redux-logic/build-lib/index.js' {
  declare module.exports: $Exports<'redux-logic/build-lib/index'>;
}
declare module 'redux-logic/build-lib/logicWrapper.js' {
  declare module.exports: $Exports<'redux-logic/build-lib/logicWrapper'>;
}
declare module 'redux-logic/build-lib/utils.js' {
  declare module.exports: $Exports<'redux-logic/build-lib/utils'>;
}
declare module 'redux-logic/dist/redux-logic.js' {
  declare module.exports: $Exports<'redux-logic/dist/redux-logic'>;
}
declare module 'redux-logic/dist/redux-logic.min.js' {
  declare module.exports: $Exports<'redux-logic/dist/redux-logic.min'>;
}
declare module 'redux-logic/src/createLogic.js' {
  declare module.exports: $Exports<'redux-logic/src/createLogic'>;
}
declare module 'redux-logic/src/createLogicAction$.js' {
  declare module.exports: $Exports<'redux-logic/src/createLogicAction$'>;
}
declare module 'redux-logic/src/createLogicMiddleware.js' {
  declare module.exports: $Exports<'redux-logic/src/createLogicMiddleware'>;
}
declare module 'redux-logic/src/index.js' {
  declare module.exports: $Exports<'redux-logic/src/index'>;
}
declare module 'redux-logic/src/logicWrapper.js' {
  declare module.exports: $Exports<'redux-logic/src/logicWrapper'>;
}
declare module 'redux-logic/src/utils.js' {
  declare module.exports: $Exports<'redux-logic/src/utils'>;
}
