// flow-typed signature: 8ac338b8aa9e84a766734a02843bb636
// flow-typed version: <<STUB>>/redux-logic-test_v^1.0.5/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-logic-test'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-logic-test' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-logic-test/build-es/createMockStore' {
  declare module.exports: any;
}

declare module 'redux-logic-test/build-es/index' {
  declare module.exports: any;
}

declare module 'redux-logic-test/build-lib/createMockStore' {
  declare module.exports: any;
}

declare module 'redux-logic-test/build-lib/index' {
  declare module.exports: any;
}

declare module 'redux-logic-test/dist/redux-logic-test' {
  declare module.exports: any;
}

declare module 'redux-logic-test/dist/redux-logic-test.min' {
  declare module.exports: any;
}

declare module 'redux-logic-test/src/createMockStore' {
  declare module.exports: any;
}

declare module 'redux-logic-test/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-logic-test/build-es/createMockStore.js' {
  declare module.exports: $Exports<'redux-logic-test/build-es/createMockStore'>;
}
declare module 'redux-logic-test/build-es/index.js' {
  declare module.exports: $Exports<'redux-logic-test/build-es/index'>;
}
declare module 'redux-logic-test/build-lib/createMockStore.js' {
  declare module.exports: $Exports<'redux-logic-test/build-lib/createMockStore'>;
}
declare module 'redux-logic-test/build-lib/index.js' {
  declare module.exports: $Exports<'redux-logic-test/build-lib/index'>;
}
declare module 'redux-logic-test/dist/redux-logic-test.js' {
  declare module.exports: $Exports<'redux-logic-test/dist/redux-logic-test'>;
}
declare module 'redux-logic-test/dist/redux-logic-test.min.js' {
  declare module.exports: $Exports<'redux-logic-test/dist/redux-logic-test.min'>;
}
declare module 'redux-logic-test/src/createMockStore.js' {
  declare module.exports: $Exports<'redux-logic-test/src/createMockStore'>;
}
declare module 'redux-logic-test/src/index.js' {
  declare module.exports: $Exports<'redux-logic-test/src/index'>;
}
