// flow-typed signature: 3ec0aed7de893ced873991135616dd34
// flow-typed version: <<STUB>>/redux-act_v^1.3.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-act'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-act' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-act/dist/redux-act' {
  declare module.exports: any;
}

declare module 'redux-act/dist/redux-act.min' {
  declare module.exports: any;
}

declare module 'redux-act/lib/assignAll' {
  declare module.exports: any;
}

declare module 'redux-act/lib/batch' {
  declare module.exports: any;
}

declare module 'redux-act/lib/bindAll' {
  declare module.exports: any;
}

declare module 'redux-act/lib/createAction' {
  declare module.exports: any;
}

declare module 'redux-act/lib/createReducer' {
  declare module.exports: any;
}

declare module 'redux-act/lib/disbatch' {
  declare module.exports: any;
}

declare module 'redux-act/lib/index' {
  declare module.exports: any;
}

declare module 'redux-act/lib/loggers/index' {
  declare module.exports: any;
}

declare module 'redux-act/lib/loggers/reduxLogger' {
  declare module.exports: any;
}

declare module 'redux-act/lib/types' {
  declare module.exports: any;
}

declare module 'redux-act/src/assignAll' {
  declare module.exports: any;
}

declare module 'redux-act/src/batch' {
  declare module.exports: any;
}

declare module 'redux-act/src/bindAll' {
  declare module.exports: any;
}

declare module 'redux-act/src/createAction' {
  declare module.exports: any;
}

declare module 'redux-act/src/createReducer' {
  declare module.exports: any;
}

declare module 'redux-act/src/disbatch' {
  declare module.exports: any;
}

declare module 'redux-act/src/index' {
  declare module.exports: any;
}

declare module 'redux-act/src/loggers/index' {
  declare module.exports: any;
}

declare module 'redux-act/src/loggers/reduxLogger' {
  declare module.exports: any;
}

declare module 'redux-act/src/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-act/dist/redux-act.js' {
  declare module.exports: $Exports<'redux-act/dist/redux-act'>;
}
declare module 'redux-act/dist/redux-act.min.js' {
  declare module.exports: $Exports<'redux-act/dist/redux-act.min'>;
}
declare module 'redux-act/lib/assignAll.js' {
  declare module.exports: $Exports<'redux-act/lib/assignAll'>;
}
declare module 'redux-act/lib/batch.js' {
  declare module.exports: $Exports<'redux-act/lib/batch'>;
}
declare module 'redux-act/lib/bindAll.js' {
  declare module.exports: $Exports<'redux-act/lib/bindAll'>;
}
declare module 'redux-act/lib/createAction.js' {
  declare module.exports: $Exports<'redux-act/lib/createAction'>;
}
declare module 'redux-act/lib/createReducer.js' {
  declare module.exports: $Exports<'redux-act/lib/createReducer'>;
}
declare module 'redux-act/lib/disbatch.js' {
  declare module.exports: $Exports<'redux-act/lib/disbatch'>;
}
declare module 'redux-act/lib/index.js' {
  declare module.exports: $Exports<'redux-act/lib/index'>;
}
declare module 'redux-act/lib/loggers/index.js' {
  declare module.exports: $Exports<'redux-act/lib/loggers/index'>;
}
declare module 'redux-act/lib/loggers/reduxLogger.js' {
  declare module.exports: $Exports<'redux-act/lib/loggers/reduxLogger'>;
}
declare module 'redux-act/lib/types.js' {
  declare module.exports: $Exports<'redux-act/lib/types'>;
}
declare module 'redux-act/src/assignAll.js' {
  declare module.exports: $Exports<'redux-act/src/assignAll'>;
}
declare module 'redux-act/src/batch.js' {
  declare module.exports: $Exports<'redux-act/src/batch'>;
}
declare module 'redux-act/src/bindAll.js' {
  declare module.exports: $Exports<'redux-act/src/bindAll'>;
}
declare module 'redux-act/src/createAction.js' {
  declare module.exports: $Exports<'redux-act/src/createAction'>;
}
declare module 'redux-act/src/createReducer.js' {
  declare module.exports: $Exports<'redux-act/src/createReducer'>;
}
declare module 'redux-act/src/disbatch.js' {
  declare module.exports: $Exports<'redux-act/src/disbatch'>;
}
declare module 'redux-act/src/index.js' {
  declare module.exports: $Exports<'redux-act/src/index'>;
}
declare module 'redux-act/src/loggers/index.js' {
  declare module.exports: $Exports<'redux-act/src/loggers/index'>;
}
declare module 'redux-act/src/loggers/reduxLogger.js' {
  declare module.exports: $Exports<'redux-act/src/loggers/reduxLogger'>;
}
declare module 'redux-act/src/types.js' {
  declare module.exports: $Exports<'redux-act/src/types'>;
}
