// flow-typed signature: 2239f856746b227ce6a33737aa166d3d
// flow-typed version: <<STUB>>/redux-auth-wrapper_v^2.0.1/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-auth-wrapper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-auth-wrapper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-auth-wrapper/authWrapper' {
  declare module.exports: any;
}

declare module 'redux-auth-wrapper/connectedAuthWrapper' {
  declare module.exports: any;
}

declare module 'redux-auth-wrapper/helper/redirect' {
  declare module.exports: any;
}

declare module 'redux-auth-wrapper/history3/locationHelper' {
  declare module.exports: any;
}

declare module 'redux-auth-wrapper/history3/redirect' {
  declare module.exports: any;
}

declare module 'redux-auth-wrapper/history4/locationHelper' {
  declare module.exports: any;
}

declare module 'redux-auth-wrapper/history4/redirect' {
  declare module.exports: any;
}

declare module 'redux-auth-wrapper/redirect' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-auth-wrapper/authWrapper.js' {
  declare module.exports: $Exports<'redux-auth-wrapper/authWrapper'>;
}
declare module 'redux-auth-wrapper/connectedAuthWrapper.js' {
  declare module.exports: $Exports<'redux-auth-wrapper/connectedAuthWrapper'>;
}
declare module 'redux-auth-wrapper/helper/redirect.js' {
  declare module.exports: $Exports<'redux-auth-wrapper/helper/redirect'>;
}
declare module 'redux-auth-wrapper/history3/locationHelper.js' {
  declare module.exports: $Exports<'redux-auth-wrapper/history3/locationHelper'>;
}
declare module 'redux-auth-wrapper/history3/redirect.js' {
  declare module.exports: $Exports<'redux-auth-wrapper/history3/redirect'>;
}
declare module 'redux-auth-wrapper/history4/locationHelper.js' {
  declare module.exports: $Exports<'redux-auth-wrapper/history4/locationHelper'>;
}
declare module 'redux-auth-wrapper/history4/redirect.js' {
  declare module.exports: $Exports<'redux-auth-wrapper/history4/redirect'>;
}
declare module 'redux-auth-wrapper/index' {
  declare module.exports: $Exports<'redux-auth-wrapper'>;
}
declare module 'redux-auth-wrapper/index.js' {
  declare module.exports: $Exports<'redux-auth-wrapper'>;
}
declare module 'redux-auth-wrapper/redirect.js' {
  declare module.exports: $Exports<'redux-auth-wrapper/redirect'>;
}
