// flow-typed signature: d023d457ab33f94a160fcba971c8981f
// flow-typed version: <<STUB>>/simple-oauth2_v^1.3.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'simple-oauth2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'simple-oauth2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'simple-oauth2/lib/client/access-token' {
  declare module.exports: any;
}

declare module 'simple-oauth2/lib/client/auth-code' {
  declare module.exports: any;
}

declare module 'simple-oauth2/lib/client/client' {
  declare module.exports: any;
}

declare module 'simple-oauth2/lib/client/password' {
  declare module.exports: any;
}

declare module 'simple-oauth2/lib/core' {
  declare module.exports: any;
}

declare module 'simple-oauth2/lib/error' {
  declare module.exports: any;
}

declare module 'simple-oauth2/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'simple-oauth2/index' {
  declare module.exports: $Exports<'simple-oauth2'>;
}
declare module 'simple-oauth2/index.js' {
  declare module.exports: $Exports<'simple-oauth2'>;
}
declare module 'simple-oauth2/lib/client/access-token.js' {
  declare module.exports: $Exports<'simple-oauth2/lib/client/access-token'>;
}
declare module 'simple-oauth2/lib/client/auth-code.js' {
  declare module.exports: $Exports<'simple-oauth2/lib/client/auth-code'>;
}
declare module 'simple-oauth2/lib/client/client.js' {
  declare module.exports: $Exports<'simple-oauth2/lib/client/client'>;
}
declare module 'simple-oauth2/lib/client/password.js' {
  declare module.exports: $Exports<'simple-oauth2/lib/client/password'>;
}
declare module 'simple-oauth2/lib/core.js' {
  declare module.exports: $Exports<'simple-oauth2/lib/core'>;
}
declare module 'simple-oauth2/lib/error.js' {
  declare module.exports: $Exports<'simple-oauth2/lib/error'>;
}
declare module 'simple-oauth2/lib/utils.js' {
  declare module.exports: $Exports<'simple-oauth2/lib/utils'>;
}
