// flow-typed signature: 678ac367d5ef6797bb2d456b3824e35f
// flow-typed version: <<STUB>>/stylefmt_v^6.0.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylefmt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylefmt' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stylefmt/bin/cli' {
  declare module.exports: any;
}

declare module 'stylefmt/lib/formatAtRuleParams' {
  declare module.exports: any;
}

declare module 'stylefmt/lib/formatAtRules' {
  declare module.exports: any;
}

declare module 'stylefmt/lib/formatColors' {
  declare module.exports: any;
}

declare module 'stylefmt/lib/formatComments' {
  declare module.exports: any;
}

declare module 'stylefmt/lib/formatDecls' {
  declare module.exports: any;
}

declare module 'stylefmt/lib/formatOrder' {
  declare module.exports: any;
}

declare module 'stylefmt/lib/formatRules' {
  declare module.exports: any;
}

declare module 'stylefmt/lib/formatSassVariables' {
  declare module.exports: any;
}

declare module 'stylefmt/lib/formatSelectors' {
  declare module.exports: any;
}

declare module 'stylefmt/lib/formatShorthand' {
  declare module.exports: any;
}

declare module 'stylefmt/lib/formatTransforms' {
  declare module.exports: any;
}

declare module 'stylefmt/lib/formatValues' {
  declare module.exports: any;
}

declare module 'stylefmt/lib/formatZeros' {
  declare module.exports: any;
}

declare module 'stylefmt/lib/getIndent' {
  declare module.exports: any;
}

declare module 'stylefmt/lib/hasBlock' {
  declare module.exports: any;
}

declare module 'stylefmt/lib/hasDecls' {
  declare module.exports: any;
}

declare module 'stylefmt/lib/hasRules' {
  declare module.exports: any;
}

declare module 'stylefmt/lib/params' {
  declare module.exports: any;
}

declare module 'stylefmt/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stylefmt/bin/cli.js' {
  declare module.exports: $Exports<'stylefmt/bin/cli'>;
}
declare module 'stylefmt/index' {
  declare module.exports: $Exports<'stylefmt'>;
}
declare module 'stylefmt/index.js' {
  declare module.exports: $Exports<'stylefmt'>;
}
declare module 'stylefmt/lib/formatAtRuleParams.js' {
  declare module.exports: $Exports<'stylefmt/lib/formatAtRuleParams'>;
}
declare module 'stylefmt/lib/formatAtRules.js' {
  declare module.exports: $Exports<'stylefmt/lib/formatAtRules'>;
}
declare module 'stylefmt/lib/formatColors.js' {
  declare module.exports: $Exports<'stylefmt/lib/formatColors'>;
}
declare module 'stylefmt/lib/formatComments.js' {
  declare module.exports: $Exports<'stylefmt/lib/formatComments'>;
}
declare module 'stylefmt/lib/formatDecls.js' {
  declare module.exports: $Exports<'stylefmt/lib/formatDecls'>;
}
declare module 'stylefmt/lib/formatOrder.js' {
  declare module.exports: $Exports<'stylefmt/lib/formatOrder'>;
}
declare module 'stylefmt/lib/formatRules.js' {
  declare module.exports: $Exports<'stylefmt/lib/formatRules'>;
}
declare module 'stylefmt/lib/formatSassVariables.js' {
  declare module.exports: $Exports<'stylefmt/lib/formatSassVariables'>;
}
declare module 'stylefmt/lib/formatSelectors.js' {
  declare module.exports: $Exports<'stylefmt/lib/formatSelectors'>;
}
declare module 'stylefmt/lib/formatShorthand.js' {
  declare module.exports: $Exports<'stylefmt/lib/formatShorthand'>;
}
declare module 'stylefmt/lib/formatTransforms.js' {
  declare module.exports: $Exports<'stylefmt/lib/formatTransforms'>;
}
declare module 'stylefmt/lib/formatValues.js' {
  declare module.exports: $Exports<'stylefmt/lib/formatValues'>;
}
declare module 'stylefmt/lib/formatZeros.js' {
  declare module.exports: $Exports<'stylefmt/lib/formatZeros'>;
}
declare module 'stylefmt/lib/getIndent.js' {
  declare module.exports: $Exports<'stylefmt/lib/getIndent'>;
}
declare module 'stylefmt/lib/hasBlock.js' {
  declare module.exports: $Exports<'stylefmt/lib/hasBlock'>;
}
declare module 'stylefmt/lib/hasDecls.js' {
  declare module.exports: $Exports<'stylefmt/lib/hasDecls'>;
}
declare module 'stylefmt/lib/hasRules.js' {
  declare module.exports: $Exports<'stylefmt/lib/hasRules'>;
}
declare module 'stylefmt/lib/params.js' {
  declare module.exports: $Exports<'stylefmt/lib/params'>;
}
declare module 'stylefmt/lib/util.js' {
  declare module.exports: $Exports<'stylefmt/lib/util'>;
}
