
CREATE TABLE TEST.COMPANY (
	ID                   varchar2(50)  NOT NULL,
	CODE                 varchar2(100)  ,
	NAME                 varchar2(200)  ,
	TYPE                 varchar2(30)  ,
	BUSINESS_LICENSE     varchar2(50)  ,
	ACCOUNT              varchar2(50)  ,
	LEGAL_CONTACT        varchar2(50)  ,
	LEGAL_CONTACT_PHONE  varchar2(20)  ,
	LEGAL_CONTACT_CODE   varchar2(30)  ,
	TAX_CERT_NO          varchar2(30)  ,
	COMPANY_ADDRESS      varchar2(100)  ,
	COMPANY_ADDRESS_DETAIL varchar2(500)  ,
	ACCOUNT_BANK         varchar2(200)  ,
	CREATE_DATETIME      date  ,
	MODIFY_DATETIME      date  ,
	CONSTRAINT SYS_C007077 PRIMARY KEY ( ID ) ,
	CONSTRAINT SYS_C007078 UNIQUE ( CODE ) ,
	CONSTRAINT SYS_C007079 UNIQUE ( NAME )
 );

COMMENT ON TABLE TEST.COMPANY IS '投标单位';

COMMENT ON COLUMN TEST.COMPANY.CODE IS '企业代码';

COMMENT ON COLUMN TEST.COMPANY.NAME IS '单位名称';

COMMENT ON COLUMN TEST.COMPANY.TYPE IS '单位类别 参考14.4.7 主体类别';

COMMENT ON COLUMN TEST.COMPANY.BUSINESS_LICENSE IS '营业执照(三证合一 即统一社会信用代码 特指三证合一营业执照"统一社会信息用代码" 请勿填写其他证书编号)';

COMMENT ON COLUMN TEST.COMPANY.ACCOUNT IS '投标单位基本账户';

COMMENT ON COLUMN TEST.COMPANY.LEGAL_CONTACT IS '联系人';

COMMENT ON COLUMN TEST.COMPANY.LEGAL_CONTACT_PHONE IS '联系人电话';

COMMENT ON COLUMN TEST.COMPANY.LEGAL_CONTACT_CODE IS '联系人证件号码(身份证)';

COMMENT ON COLUMN TEST.COMPANY.TAX_CERT_NO IS '国税纳税识别号';

COMMENT ON COLUMN TEST.COMPANY.COMPANY_ADDRESS IS '企业注册地址';

COMMENT ON COLUMN TEST.COMPANY.COMPANY_ADDRESS_DETAIL IS '企业详细地址';

COMMENT ON COLUMN TEST.COMPANY.ACCOUNT_BANK IS '投标单位开户行';

COMMENT ON COLUMN TEST.COMPANY.CREATE_DATETIME IS '创建时间';
