
INSERT INTO XYGH.COMPANY
  (
  ID,CODE,NAME,TYPE,BUSINESS_LICENSE,
  ACCOUNT,LEGAL_CONTACT,LEGAL_CONTACT_PHONE,
  LEGAL_CONTACT_CODE)
VALUES(
    'LOTUC-XXXX-XXXX-XXXX-XXXXXXXXXXXX', 'lotuc-code', 'LOTUC有限公司', '2', 'lc-license',
    'lotuc', 'lotuc', '13888888888', '888888'
);